apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
#  labels:
#    app: kubernetes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-homework
  template:
    metadata:
      labels:
        app: kubernetes-homework
    spec:
      containers:
        - image: imalouhov/kubernetes-homework:0.0.1
          name: homework-pod
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP