apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
#  labels:
#    app: kubernetes-homework
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-homework
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080